spring.application.name=AMS
server.port=8081

#Local Database
spring.datasource.url=jdbc:mysql://localhost:3306/AMS
spring.datasource.username=root
spring.datasource.password=umar111
spring.jpa.hibernate.ddl-auto=update
jwt.secret.key=v8Xb2R0JSI1cH2M8qGuh3uHEVZ+YQvLpYiXxvnMHO5o=