#
# Build stage
#
FROM maven:3.9.15-openjdk-17 AS build
COPY . .
RUN mvn clean install

#
# Package stage
#
FROM eclipse-temurin:17-jdk
COPY --from=build /target/AMS-0.0.1-SNAPSHOT.jar ams.jar
# ENV PORT=8080
EXPOSE 8081
ENTRYPOINT ["java","-jar","ams.jar"]