apiVersion: apps/v1
kind: Deployment
metadata:
  name: contact360-app
  labels:
    app: contact360-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: contact360-app
  template:
    metadata:
      labels:
        app: contact360-app
    spec:
      #hostNetwork: true
      containers:
      - name: contact360-app
        image: syedhuzaifafazal/contact360-app:8
        ports:
        - containerPort: 8080
